function CONTRASTS_processing(repoRoot)

close all

% Input/output directories
rawDir = fullfile(repoRoot, 'data', 'raw');
processedDir = fullfile(repoRoot, 'data', 'processed');
if ~exist(processedDir, 'dir')
    mkdir(processedDir)
end

% Input file
inputFile = fullfile(rawDir, 'sea-ice_cores_density_PS149.tab');

% Output file
outputFile = fullfile(processedDir, 'Summary_CONTRASTS.mat');

txt = fileread(inputFile);
endHeader = strfind(txt,'*/');
dataTxt = strtrim(txt(endHeader(1)+2:end));

tmpFile = [tempname '.tab'];
fid = fopen(tmpFile,'w');
fwrite(fid,dataTxt);
fclose(fid);

opts = detectImportOptions(tmpFile, ...
    'FileType','text', ...
    'Delimiter','\t', ...
    'VariableNamingRule','preserve');

Tfull = readtable(tmpFile,opts);
delete(tmpFile)

cols = [2 3 4 7 8 11 13 14 15 16 17 18 23 24];

T = Tfull(:,cols);

T.Properties.VariableNames = { ...
    'DateTime', ...
    'Latitude', ...
    'Longitude', ...
    'SeaIceThickness_m', ...
    'Core', ...
    'IceAge', ...
    'DepthTop_m', ...
    'DepthBottom_m', ...
    'SeaIceSalinity', ...
    'Tlab_C', ...
    'Temperature_C', ...
    'Density_lab_kgm3', ...
    'SnowThickness_m', ...
    'Comment'};

T.DateTime = datetime(T.DateTime, ...
    'InputFormat','yyyy-MM-dd''T''HH:mm:ss');

T.Temperature_C_limited = min(-0.1,T.Temperature_C);

S = T.SeaIceSalinity;
rho = T.Density_lab_kgm3;
Tlab = T.Tlab_C;
Ti = T.Temperature_C_limited;

T.BrineVolume = nan(height(T),1);

T.GasVolume_lab = nan(height(T),1);
T.GasVolume_connected = nan(height(T),1);
T.GasVolume_disconnected = nan(height(T),1);

T.Density_insitu_connected_kgm3 = nan(height(T),1);
T.Density_insitu_disconnected_kgm3 = nan(height(T),1);

idx = ~isnan(S) & ~isnan(rho) & ~isnan(Tlab) & ~isnan(Ti);

Si = S(idx);
rho_lab = rho(idx);

Tlab_i = Tlab(idx);
Ti_i = Ti(idx);

[F1_pr,F2_pr] = F1F2_seaice(Tlab_i);
[F1_i,F2_i] = F1F2_seaice(Ti_i);

rhoi_pr = 917 - 0.1403*Tlab_i;
rhoi_i  = 917 - 0.1403*Ti_i;

vb_pr = rho_lab .* Si ./ F1_pr;

vg_pr = max(0, ...
    1 - rho_lab .* ...
    (F1_pr - rhoi_pr .* Si/1000 .* F2_pr) ./ ...
    (rhoi_pr .* F1_pr));

F3_pr = rhoi_pr .* Si/1000 ./ ...
    (F1_pr - rhoi_pr .* Si/1000 .* F2_pr);

F3_i = rhoi_i .* Si/1000 ./ ...
    (F1_i - rhoi_i .* Si/1000 .* F2_i);

vb_raw = vb_pr .* F1_pr ./ F1_i / 1000;

vb_export = vb_raw;
vb_export(vb_export > 0.4 | vb_export < 0) = NaN;

vb_calc = vb_raw;
vb_calc(vb_calc > 0.4 | vb_calc < 0) = 0.4;

% Connected pores (Eq. 21)

A = ...
    (rhoi_i ./ rhoi_pr) .* ...
    (F3_pr ./ F3_i) .* ...
    (F1_pr ./ F1_i);

vg_connected = max(0, ...
    1 - (1 - vg_pr) .* A);

vg_disconnected = vg_pr;

rho_si_connected = ...
    (1 - vg_connected) .* ...
    rhoi_i .* F1_i ./ ...
    (F1_i - rhoi_i .* Si/1000 .* F2_i);

rho_si_disconnected = ...
    (1 - vg_disconnected) .* ...
    rhoi_i .* F1_i ./ ...
    (F1_i - rhoi_i .* Si/1000 .* F2_i);

rho_si_connected(isnan(vb_calc)) = NaN;
rho_si_disconnected(isnan(vb_calc)) = NaN;

T.BrineVolume(idx) = vb_export;

T.GasVolume_lab(idx) = vg_pr;
T.GasVolume_connected(idx) = vg_connected;
T.GasVolume_disconnected(idx) = vg_disconnected;

T.Density_insitu_connected_kgm3(idx) = ...
    rho_si_connected;

T.Density_insitu_disconnected_kgm3(idx) = ...
    rho_si_disconnected;

idxFalseBottom = contains( ...
    lower(string(T.Comment)), ...
    'false bottom');

idxNaNDensity = isnan(T.Density_lab_kgm3);

TavgInput = T(~idxFalseBottom & ~idxNaNDensity,:);

numericVars = varfun( ...
    @isnumeric, ...
    TavgInput, ...
    'OutputFormat','uniform');

excludeFromAverages = ismember( ...
    TavgInput.Properties.VariableNames, ...
    {'Core','DepthTop_m','DepthBottom_m'});

numNames = TavgInput.Properties.VariableNames( ...
    numericVars & ~excludeFromAverages);

Tavg = groupsummary( ...
    TavgInput, ...
    'Core', ...
    'mean', ...
    numNames);

if ismember('GroupCount',Tavg.Properties.VariableNames)
    Tavg.GroupCount = [];
end

Tavg.Properties.VariableNames = erase( ...
    Tavg.Properties.VariableNames, ...
    'mean_');

coreInfo = groupsummary( ...
    TavgInput(:,{'Core','DateTime'}), ...
    'Core', ...
    'min', ...
    'DateTime');

if ismember('GroupCount',coreInfo.Properties.VariableNames)
    coreInfo.GroupCount = [];
end

coreInfo.Properties.VariableNames{'min_DateTime'} = ...
    'DateTime';

Tavg = outerjoin( ...
    coreInfo, ...
    Tavg, ...
    'Keys','Core', ...
    'MergeKeys',true, ...
    'Type','right');

Tavg = movevars(Tavg,'DateTime','After','Core');

TavgInput.IceAge = upper(string(TavgInput.IceAge));

TavgInput.IceAge(TavgInput.IceAge == "SMYI") = "MYI";

[G,coreList] = findgroups(TavgInput.Core);

iceAgeFirst = splitapply(@(x) x(find(x ~= "",1,'first')), ...
    TavgInput.IceAge, G);

iceAgeInfo = table(coreList, iceAgeFirst, ...
    'VariableNames', {'Core','IceAge'});

Tavg = outerjoin( ...
    iceAgeInfo, ...
    Tavg, ...
    'Keys','Core', ...
    'MergeKeys',true, ...
    'Type','right');

Tavg = movevars(Tavg,'IceAge','After','DateTime');

fprintf('Imported CONTRASTS dataset.\n')
fprintf('Processed %d ice cores.\n', height(Tavg))
fprintf('Output saved to:\n%s\n', outputFile)

dataset = repmat("CONTRASTS SYI",height(Tavg),1);
idxFYI = upper(string(Tavg.IceAge)) == "FYI";
dataset(idxFYI) = "CONTRASTS FYI";
core = Tavg.Core;
date = Tavg.DateTime;
ice_age = string(Tavg.IceAge);
temperature_C = Tavg.Temperature_C_limited;
density_lab_kgm3 = Tavg.Density_lab_kgm3;
density_insitu_connected_kgm3 = Tavg.Density_insitu_connected_kgm3;
density_insitu_disconnected_kgm3 = Tavg.Density_insitu_disconnected_kgm3;
ice_thickness_m = Tavg.SeaIceThickness_m;
snow_thickness_m = Tavg.SnowThickness_m;
lat_degN = Tavg.Latitude;
lon_degE = Tavg.Longitude;

Summary_PS149 = table( ...
    dataset, ...
    core, ...
    date, ...
    ice_age, ...
    temperature_C, ...
    density_lab_kgm3, ...
    density_insitu_connected_kgm3, ...
    density_insitu_disconnected_kgm3, ...
    ice_thickness_m, ...
    snow_thickness_m, ...
    lat_degN, ...
    lon_degE, ...
    'VariableNames',{ ...
    'dataset', ...
    'core', ...
    'date', ...
    'ice_age', ...
    'temperature_C', ...
    'density_lab_kgm3', ...
    'density_insitu_connected_kgm3', ...
    'density_insitu_disconnected_kgm3', ...
    'ice_thickness_m', ...
    'snow_thickness_m', ...
    'lat_degN', ...
    'lon_degE'});

save(outputFile,'Summary_PS149')

%% Helpers
function [F1,F2] = F1F2_seaice(T)

F1 = -4.732 - 22.45*T - 0.6397*T.^2 - 0.01074*T.^3;
F2 = 8.903e-2 - 1.763e-2*T - 5.33e-4*T.^2 - 8.801e-6*T.^3;

idxWarm = T > -2;

F1(idxWarm) = -4.1221e-2 - 18.407*T(idxWarm) + ...
    0.58402*T(idxWarm).^2 + 0.21454*T(idxWarm).^3;

F2(idxWarm) = 9.0312e-2 - 0.016111*T(idxWarm) + ...
    1.2291e-4*T(idxWarm).^2 + 1.3603e-4*T(idxWarm).^3;

idxCold = T < -22.9;

F1(idxCold) = 9899 + 1309*T(idxCold) + ...
    55.27*T(idxCold).^2 + 0.7160*T(idxCold).^3;

F2(idxCold) = 8.547 + 1.089*T(idxCold) + ...
    0.04518*T(idxCold).^2 + 5.819e-4*T(idxCold).^3;

end

end