function make_figure3(repoRoot)

%
% MAKE_FIGURE3
%
% Generates Figure 3 for the manuscript: CryoSat‑2 Arctic sea‑ice density
% and thickness climatology for February and July 2011–2023.
%
% Compares three sea‑ice density parameterizations:
%   • A2010 – Alexandrov et al. (2010)
%   • J2022 – Jutila et al. (2022)
%   • S2026 – This study
%
% Figure layout:
%   Row 1: February climatology (2011–2023)
%   Row 2: July climatology (2011–2023)
%
%   Columns 1–3: Mean sea‑ice density maps (A2010, J2022, S2026)
%   Column 4: Sea‑ice thickness probability density functions
%
% Required input files (placed in data/cs2/):
%   uit_sit_v2northpolarstereo_80km_feb_2011-2023_v3p0.nc
%   uit_sit_v2northpolarstereo_80km_jul_2011-2023_v3p0.nc
%
% Output:
%   figures/Fig3.png
%
% Notes:
%   • Missing values near the pole are filled using inpaint_nans.
%   • Sea‑ice concentration < 15% is masked.
%

% Suppress Mapping Toolbox deprecation warnings generated internally by ncpolarm.
warning('off','map:removing:mfwdtran')
warning('off','map:removing:minvtran')

% February dataset.
filename_feb = fullfile(repoRoot, 'data', 'cs2', ...
    'uit_sit_v2northpolarstereo_80km_feb_2011-2023_v3p0.nc');

grid_lat = ncread(filename_feb,'latitude');
grid_lon = ncread(filename_feb,'longitude');
sic_feb = ncread(filename_feb,'sic');

sit_A2010_feb = ncread(filename_feb,'sit_A2010');
si_dens_A2010_feb = ncread(filename_feb,'si_dens_A2010');

sit_J2021_feb = ncread(filename_feb,'sit_J2021');
si_dens_J2021_feb = ncread(filename_feb,'si_dens_J2021');

sit_S2026_feb = ncread(filename_feb,'sit_S2026');
si_dens_S2026_feb = ncread(filename_feb,'si_dens_S2026');

% CryoSat-2 monthly SIT products use a fixed 80 km polar stereographic grid.
filename_jul = fullfile(repoRoot, 'data', 'cs2', ...
    'uit_sit_v2northpolarstereo_80km_jul_2011-2023_v3p0.nc');

sic_jul = ncread(filename_jul,'sic');

sit_A2010_jul = ncread(filename_jul,'sit_A2010');
si_dens_A2010_jul = ncread(filename_jul,'si_dens_A2010');

sit_J2021_jul = ncread(filename_jul,'sit_J2021');
si_dens_J2021_jul = ncread(filename_jul,'si_dens_J2021');

sit_S2026_jul = ncread(filename_jul,'sit_S2026');
si_dens_S2026_jul = ncread(filename_jul,'si_dens_S2026');

% Reversed Viridis colormap.
cmap = flipud(viridis(128));

% Density contour levels and sea-ice thickness histogram bin edges.
c_int = 880:2.5:940;
sit_int = 0:0.1:5;

% Create the two-row, four-column figure.
fig1 = figure(1);
clf(fig1)

set(fig1, ...
    'Units','pixels', ...
    'Position',[100 100 1617 768], ...
    'Color','white')

tl = tiledlayout(fig1,2,4, ...
    'TileSpacing','compact');

% February: A2010 density map.
ax1 = nexttile(tl);

% evalc captures the command-window output produced internally by ncpolarm,
% including the repeated "Northern Hemisphere" message.
evalc("ncpolarm('lat',68,'lon',0);");

temp = nanmean(si_dens_A2010_feb,3);

% Fill missing values near the pole where CryoSat-2 has no coverage.
temp2 = inpaint_nans(temp,1);
idxPole = grid_lat > 88 & isnan(temp);
temp(idxPole) = temp2(idxPole);

% Apply spatial and sea-ice-concentration masks.
temp(grid_lat > 88.5 | ...
     temp == 0 | ...
     nanmean(sic_feb,3) < 15) = NaN;

contourfm(grid_lat,grid_lon,temp,c_int, ...
    'LineStyle','none')

contourm(grid_lat,grid_lon,nanmean(sic_feb,3), ...
    [15 15], ...
    'k', ...
    'Fill','off', ...
    'LineWidth',0.5)

clim(ax1,[min(c_int)-0.01 max(c_int)])
colormap(ax1,cmap)

textm(61.5,49.5,'A2010', ...
    'FontSize',20, ...
    'FontWeight','normal', ...
    'HorizontalAlignment','right', ...
    'BackgroundColor','white', ...
    'Margin',0.5)

text(ax1,-0.05,0.5,'Feb 2011-2023', ...
    'Units','normalized', ...
    'Rotation',90, ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','bottom', ...
    'FontSize',16, ...
    'FontWeight','normal')

text(ax1,-0.13,1.02,'(a)', ...
    'Units','normalized', ...
    'FontSize',12, ...
    'FontWeight','normal', ...
    'Clipping','off')

% February: J2022 density map.
ax2 = nexttile(tl);
evalc("ncpolarm('lat',68,'lon',0);");

temp = nanmean(si_dens_J2021_feb,3);

temp2 = inpaint_nans(temp,1);
idxPole = grid_lat > 88 & isnan(temp);
temp(idxPole) = temp2(idxPole);

% Mask out open water and unreliable grid cells:
%   - lat > 88.5°: region outside reliable CS2 coverage
%   - temp == 0: missing density values
%   - SIC < 15%: standard threshold for defining sea ice presence

temp(grid_lat > 88.5 | ...
     temp == 0 | ...
     nanmean(sic_feb,3) < 15) = NaN;

contourfm(grid_lat,grid_lon,temp,c_int, ...
    'LineStyle','none')

contourm(grid_lat,grid_lon,nanmean(sic_feb,3), ...
    [15 15], ...
    'k', ...
    'Fill','off', ...
    'LineWidth',0.5)

clim(ax2,[min(c_int)-0.01 max(c_int)])
colormap(ax2,cmap)

textm(61.5,49.5,'J2022', ...
    'FontSize',20, ...
    'FontWeight','normal', ...
    'HorizontalAlignment','right', ...
    'BackgroundColor','white', ...
    'Margin',0.5)

text(ax2,-0.13,1.02,'(b)', ...
    'Units','normalized', ...
    'FontSize',12, ...
    'FontWeight','normal', ...
    'Clipping','off')

% February: density map from this study.
ax3 = nexttile(tl);
evalc("ncpolarm('lat',68,'lon',0);");

temp = nanmean(si_dens_S2026_feb,3);

temp2 = inpaint_nans(temp,1);
idxPole = grid_lat > 88 & isnan(temp);
temp(idxPole) = temp2(idxPole);

temp(grid_lat > 88.5 | ...
     temp == 0 | ...
     nanmean(sic_feb,3) < 15) = NaN;

contourfm(grid_lat,grid_lon,temp,c_int, ...
    'LineStyle','none')

contourm(grid_lat,grid_lon,nanmean(sic_feb,3), ...
    [15 15], ...
    'k', ...
    'Fill','off', ...
    'LineWidth',0.5)

clim(ax3,[min(c_int)-0.01 max(c_int)])
colormap(ax3,cmap)

textm(61.5,49.5,'This Study', ...
    'FontSize',20, ...
    'FontWeight','normal', ...
    'HorizontalAlignment','right', ...
    'BackgroundColor','white', ...
    'Margin',0.5)

text(ax3,-0.13,1.02,'(c)', ...
    'Units','normalized', ...
    'FontSize',12, ...
    'FontWeight','normal', ...
    'Clipping','off')

% February: thickness probability density functions.
ax4 = nexttile(tl);
cla(ax4)
box(ax4,'on')
grid(ax4,'on')
hold(ax4,'on')

xlabel(ax4,'Sea-ice thickness (m)')
ylabel(ax4,'PDF')

% Histogram objects are hidden from the legend because some MATLAB
% versions render stair-histogram legend samples as blank.
histogram(ax4,sit_A2010_feb,sit_int, ...
    'Normalization','pdf', ...
    'EdgeColor',cmap(1,:), ...
    'LineWidth',2, ...
    'DisplayStyle','stairs', ...
    'HandleVisibility','off')

histogram(ax4,sit_J2021_feb,sit_int, ...
    'Normalization','pdf', ...
    'EdgeColor',cmap(64,:), ...
    'LineWidth',2, ...
    'DisplayStyle','stairs', ...
    'HandleVisibility','off')

histogram(ax4,sit_S2026_feb,sit_int, ...
    'Normalization','pdf', ...
    'EdgeColor',cmap(128,:), ...
    'LineWidth',2, ...
    'DisplayStyle','stairs', ...
    'HandleVisibility','off')

% Proxy lines ensure consistent legend colors and formatting.
p1 = plot(ax4,NaN,NaN,'-', ...
    'Color',cmap(1,:), ...
    'LineWidth',2);

p2 = plot(ax4,NaN,NaN,'-', ...
    'Color',cmap(64,:), ...
    'LineWidth',2);

p3 = plot(ax4,NaN,NaN,'-', ...
    'Color',cmap(128,:), ...
    'LineWidth',2);

xticks(ax4,0:1:5)

legend(ax4,[p1 p2 p3], ...
    {'A2010','J2022','This Study'}, ...
    'Location','northeast')

set(ax4,'FontSize',12)

text(ax4,-0.23,1.02,'(d)', ...
    'Units','normalized', ...
    'FontSize',12, ...
    'FontWeight','normal', ...
    'Clipping','off')

% July: A2010 density map.
ax5 = nexttile(tl);
evalc("ncpolarm('lat',68,'lon',0);");

temp = nanmean(si_dens_A2010_jul,3);

temp2 = inpaint_nans(temp,1);
idxPole = grid_lat > 88 & isnan(temp);
temp(idxPole) = temp2(idxPole);

temp(grid_lat > 88.5 | ...
     temp == 0 | ...
     nanmean(sic_jul,3) < 15) = NaN;

contourfm(grid_lat,grid_lon,temp,c_int, ...
    'LineStyle','none')

contourm(grid_lat,grid_lon,nanmean(sic_jul,3), ...
    [15 15], ...
    'k', ...
    'Fill','off', ...
    'LineWidth',0.5)

clim(ax5,[min(c_int)-0.01 max(c_int)])
colormap(ax5,cmap)

textm(61.5,49.5,'A2010', ...
    'FontSize',20, ...
    'FontWeight','normal', ...
    'HorizontalAlignment','right', ...
    'BackgroundColor','white', ...
    'Margin',0.5)

text(ax5,-0.05,0.5,'July 2011-2023', ...
    'Units','normalized', ...
    'Rotation',90, ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','bottom', ...
    'FontSize',16, ...
    'FontWeight','normal')

text(ax5,-0.13,1.02,'(e)', ...
    'Units','normalized', ...
    'FontSize',12, ...
    'FontWeight','normal', ...
    'Clipping','off')

% July: J2022 density map.
ax6 = nexttile(tl);
evalc("ncpolarm('lat',68,'lon',0);");

temp = nanmean(si_dens_J2021_jul,3);

temp2 = inpaint_nans(temp,1);
idxPole = grid_lat > 88 & isnan(temp);
temp(idxPole) = temp2(idxPole);

temp(grid_lat > 88.5 | ...
     temp == 0 | ...
     nanmean(sic_jul,3) < 15) = NaN;

contourfm(grid_lat,grid_lon,temp,c_int, ...
    'LineStyle','none')

contourm(grid_lat,grid_lon,nanmean(sic_jul,3), ...
    [15 15], ...
    'k', ...
    'Fill','off', ...
    'LineWidth',0.5)

clim(ax6,[min(c_int)-0.01 max(c_int)])
colormap(ax6,cmap)

textm(61.5,49.5,'J2022', ...
    'FontSize',20, ...
    'FontWeight','normal', ...
    'HorizontalAlignment','right', ...
    'BackgroundColor','white', ...
    'Margin',0.5)

text(ax6,-0.13,1.02,'(f)', ...
    'Units','normalized', ...
    'FontSize',12, ...
    'FontWeight','normal', ...
    'Clipping','off')

% July: density map from this study.
ax7 = nexttile(tl);
evalc("ncpolarm('lat',68,'lon',0);");

temp = nanmean(si_dens_S2026_jul,3);

temp2 = inpaint_nans(temp,1);
idxPole = grid_lat > 88 & isnan(temp);
temp(idxPole) = temp2(idxPole);

temp(grid_lat > 88.5 | ...
     temp == 0 | ...
     nanmean(sic_jul,3) < 15) = NaN;

contourfm(grid_lat,grid_lon,temp,c_int, ...
    'LineStyle','none')

contourm(grid_lat,grid_lon,nanmean(sic_jul,3), ...
    [15 15], ...
    'k', ...
    'Fill','off', ...
    'LineWidth',0.5)

clim(ax7,[min(c_int)-0.01 max(c_int)])
colormap(ax7,cmap)

c = colorbar(ax7,'south', ...
    'FontSize',12);

c.AxisLocation = 'out';
c.Position(2) = c.Position(2) - 0.04;
c.Label.String = 'Sea-ice density (kg m^{-3})';

textm(61.5,49.5,'This Study', ...
    'FontSize',20, ...
    'FontWeight','normal', ...
    'HorizontalAlignment','right', ...
    'BackgroundColor','white', ...
    'Margin',0.5)

text(ax7,-0.13,1.02,'(g)', ...
    'Units','normalized', ...
    'FontSize',12, ...
    'FontWeight','normal', ...
    'Clipping','off')

% July: thickness probability density functions.
ax8 = nexttile(tl);
cla(ax8)
box(ax8,'on')
grid(ax8,'on')
hold(ax8,'on')

xlabel(ax8,'Sea-ice thickness (m)')
ylabel(ax8,'PDF')

histogram(ax8,sit_A2010_jul,sit_int, ...
    'Normalization','pdf', ...
    'EdgeColor',cmap(1,:), ...
    'LineWidth',2, ...
    'DisplayStyle','stairs', ...
    'HandleVisibility','off')

histogram(ax8,sit_J2021_jul,sit_int, ...
    'Normalization','pdf', ...
    'EdgeColor',cmap(64,:), ...
    'LineWidth',2, ...
    'DisplayStyle','stairs', ...
    'HandleVisibility','off')

histogram(ax8,sit_S2026_jul,sit_int, ...
    'Normalization','pdf', ...
    'EdgeColor',cmap(128,:), ...
    'LineWidth',2, ...
    'DisplayStyle','stairs', ...
    'HandleVisibility','off')

p1 = plot(ax8,NaN,NaN,'-', ...
    'Color',cmap(1,:), ...
    'LineWidth',2);

p2 = plot(ax8,NaN,NaN,'-', ...
    'Color',cmap(64,:), ...
    'LineWidth',2);

p3 = plot(ax8,NaN,NaN,'-', ...
    'Color',cmap(128,:), ...
    'LineWidth',2);

xticks(ax8,0:1:5)

legend(ax8,[p1 p2 p3], ...
    {'A2010','J2022','This Study'}, ...
    'Location','northeast')

set(ax8,'FontSize',12)

text(ax8,-0.23,1.02,'(h)', ...
    'Units','normalized', ...
    'FontSize',12, ...
    'FontWeight','normal', ...
    'Clipping','off')

% Ensure that all graphics objects are fully rendered before export.
drawnow

% Export the main figure as a 300 dpi PNG.
outputFile = fullfile(repoRoot, 'figures', 'Fig3.png');
exportgraphics(fig1, outputFile, 'Resolution',300, 'BackgroundColor','white');
fprintf('Generated Figure 3:\n%s\n', outputFile)

end